### ISSUE TITLE
Complete community profile checklist

### ISSUE THREAD

**Issue by jcohenadad** [shimming-toolbox/shimming-toolbox-py#105]
We should follow the [convention of the lab](https://www.neuro.polymtl.ca/open_source/contributing#submitting_a_pull_request), and create specific entry for shimming-toolbox

See also https://github.com/shimming-toolbox/shimming-toolbox-py/community

- [x] Use standard templates for PRs and issues
- [x] contributing.md pointing to RTD contrib guidelines
- [x] Contributing guidelines on RTD (update submission guide)
- [x] code of conduct

**Comment by jidicula** [comment]
There's a nice way to set up PR and issue templates in GitHub: https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/about-issue-and-pull-request-templates

**Comment by jcohenadad** [comment]
similar initiative from sister project: https://github.com/neuropoly/spinalcordtoolbox/wiki/PR-checklist

let's try to unify forces
